---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
    - name: install tree on all 3 ansible nodes
      apt:
       name: tree
       state: present
