---

- hosts: testnodes
  become: yes
  gather_facts: yes
  tasks:
   - name: install apache2
     apt: 
       name : apache2
       state: present


   - name: coopy index file to web servers location
     copy:
      src: index.html
      dest: /var/www/html/index.html
     notify: restart apache2


  handlers:
   - name: restart apache2
     apt:
        name: apache2
        state: started


